// <auto-generated />
using System;
using GamifiedMathDrill.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamifiedMathDrill.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231012913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.AcquiredReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredAt");

                    b.HasIndex("RewardId");

                    b.HasIndex("StudentId");

                    b.ToTable("AcquiredRewards");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.DailyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProblemId");

                    b.HasIndex("TargetDate")
                        .IsUnique();

                    b.ToTable("DailyChallenges");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.LearningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProblemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredAt");

                    b.HasIndex("ProblemId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "AnsweredAt");

                    b.ToTable("LearningRecords");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredCorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalculationType");

                    b.HasIndex("DifficultyLevel");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("RequiredPoints");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalProblems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CurrentLevelId");

                    b.HasIndex("LastLoginAt");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.AcquiredReward", b =>
                {
                    b.HasOne("GamifiedMathDrill.Core.Models.Reward", "Reward")
                        .WithMany("AcquiredRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamifiedMathDrill.Core.Models.Student", "Student")
                        .WithMany("AcquiredRewards")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.DailyChallenge", b =>
                {
                    b.HasOne("GamifiedMathDrill.Core.Models.Problem", "Problem")
                        .WithMany("DailyChallenges")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.LearningRecord", b =>
                {
                    b.HasOne("GamifiedMathDrill.Core.Models.Problem", "Problem")
                        .WithMany("LearningRecords")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamifiedMathDrill.Core.Models.Student", "Student")
                        .WithMany("LearningRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Student", b =>
                {
                    b.HasOne("GamifiedMathDrill.Core.Models.Level", "CurrentLevel")
                        .WithMany("Students")
                        .HasForeignKey("CurrentLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLevel");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Level", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Problem", b =>
                {
                    b.Navigation("DailyChallenges");

                    b.Navigation("LearningRecords");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Reward", b =>
                {
                    b.Navigation("AcquiredRewards");
                });

            modelBuilder.Entity("GamifiedMathDrill.Core.Models.Student", b =>
                {
                    b.Navigation("AcquiredRewards");

                    b.Navigation("LearningRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
